### ISSUE TITLE
Default the region to us-east-1?

### ISSUE THREAD

**Issue by devinus** [ember-cli-deploy/ember-cli-deploy-s3#41]
This would make it the same as https://github.com/ember-cli-deploy/ember-cli-deploy-s3-index

**Comment by achambers** [comment]
Hi @devinus. `region` used to be optional with a default. However this caused loads of issues for people outside us-east-1 due to unhelpful errors on the aws ask part. 

Therefore this property is now flagged as a required property which I think is the correct option. 

I'm going to close this issue now. Please reopen if you think there is something else to discuss.

**Comment by lukemelia** [comment]
@LevelbossMike we should probably update s3-index to match

**Comment by achambers** [comment]
+1 to that @lukemelia

**Comment by devinus** [comment]
Yeah, if they were consistent it would be less confusing.
