### ISSUE TITLE
Custom Expires and Cache-Control headers for index.html

### ISSUE THREAD

**Issue by andruby** [ember-cli-deploy/ember-cli-deploy-s3#49]
Hi,

I am using ember-cli-deploy-aws, which uses this addon to put objects to an S3 bucket. Unfortunately all objects get the "Cache-Control: max-age=63072000" & "Expires: 1 Jan 2030" Metadata, which is not what you want for the index.html file.

Is there a way to configure those metadata on a per file basis?

Thank you!
Andrew

**Comment by achambers** [comment]
Hi @andruby. Thanks for your questions. So those headers obviously make sense for assets as they are fingerprinted. Therefore I'd say this change wouldn't really belong in this repo. It's probably the ember-cli-deploy-s3-index repo that you want to raise this as that is the one that manages the index.html file in S3.

@LevelbossMike What are your thoughts on this?

**Comment by andruby** [comment]
I've been using ember-cli-deploy-s3 without ember-cli-deploy-s3-index because of the incompatibility warnings in both readmes.

@achambers are you using both?

**Comment by achambers** [comment]
Oh sorry mate....Ignore my comment. My mistake. So, do you have a proposal on how you think your suggestion might be implemented? In answer to your original questions, no, there is no way for that metadata to be set on a per file basis. This plugin wasn't strictly created with the index.html in mind to be honest.

What are your thoughts?

**Comment by LevelbossMike** [comment]
When deploying `index.html` to s3 with the intention to serve it to users one should use the s3-index plugin (in combination with `ember-cli-deploy-s3` for assets). I don't think there's any reason to not use the plugin (you can even serve from the same bucket if you only have access to one bucket).

There's no 'incompatibility' between both plugins the warning in the README just states that you shouldn't share a configuration object between both plugins (because of the way ember-cli-deploy reads configuration settings). This will be fixed in the future right now it's fine to do something like this in `config/deploy.js`:

``` javascript
module.exports = function(deployTarget) {
    // ..
    s3: {
      accessKeyId: process.env.AWS_KEY,
      secretAccessKey: process.env.AWS_SECRET,
      bucket: "<your-bucket>",
      region: "<the-bucket-region>"
    },

    "s3-index": {
      accessKeyId: process.env.AWS_KEY,
      secretAccessKey: process.env.AWS_SECRET,
      bucket: "<your-bucket>",
      region: "<your-bucket-region>"
    }

   // ...

  return ENV;
};
```

@andruby Are there any issues that keep you from using s3-index? There's https://github.com/Gaurav0/ember-cli-deploy-s3-pack that bundles the whole "serve everything via s3" approach. Feel free to ping me on slack if you run into problems, I'm happy to help

**Comment by andruby** [comment]
Thank you for the comprehensive answers. I'm going to use s3-index together with s3 first thing in the morning! :)

**Comment by andruby** [comment]
I'll close this issue, as there is no real need to change the headers when using both addons together.
